// frontend/src/pages/ResultPage.tsx
import { useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { Button, message, Result, Spin } from 'antd';
import { DownloadOutlined, LeftOutlined, FileWordOutlined, LoadingOutlined, CheckCircleOutlined, CloseCircleOutlined } from '@ant-design/icons';
import { getDocument, exportDocument } from '../services/documentService';
import MarkdownRenderer from '../components/MarkdownRenderer';
import type { DocumentResponse } from '../types';
import { ApiError } from '../services/request';
import { formatBeijingDateTime } from '../utils/time';
import './ResultPage.css';

export default function ResultPage() {
  const { docId } = useParams<{ docId: string }>();
  const navigate = useNavigate();
  const apiBaseUrl = import.meta.env.VITE_API_BASE_URL || 'http://localhost:8000';

  const [doc, setDoc] = useState<DocumentResponse | null>(null);
  const [loading, setLoading] = useState(true);
  const [notFound, setNotFound] = useState(false);
  const [exporting, setExporting] = useState(false);

  useEffect(() => {
    if (!docId) return;
    let isMounted = true;
    const fetchDoc = async () => {
      setLoading(true);
      try {
        const res = await getDocument(docId);
        if (isMounted) setDoc(res);
      } catch (error: unknown) {
        if (isMounted) {
          if (error instanceof ApiError && error.status === 404) {
            setNotFound(true);
          } else {
            message.error('无法加载文档，请稍后重试');
          }
        }
      } finally {
        if (isMounted) setLoading(false);
      }
    };
    fetchDoc();
    return () => { isMounted = false; };
  }, [docId]);

  const handleExport = async () => {
    if (!docId) return;
    setExporting(true);
    try {
      const res = await exportDocument(docId);
      if (res?.download_url) {
        const downloadUrl = res.download_url.startsWith('http')
          ? res.download_url
          : `${apiBaseUrl}${res.download_url}`;

        const anchor = document.createElement('a');
        anchor.href = downloadUrl;
        anchor.target = '_blank';
        anchor.rel = 'noopener noreferrer';
        anchor.download = res.filename || '';
        document.body.appendChild(anchor);
        anchor.click();
        anchor.remove();
        message.success('已触发文书下载');
      } else if (res?.message) {
        message.info(`下载状态: ${res.message}`);
      } else {
        message.error('暂未获取到可用的下载地址');
      }
    } catch (error: unknown) {
      if (error instanceof ApiError) {
        message.error(error.message);
      } else {
        message.error('导出请求失败，请稍后重试');
      }
    } finally {
      setExporting(false);
    }
  };

  if (notFound) {
    return (
      <div className="page-container glass-card" style={{ marginTop: '10vh' }}>
        <Result
          status="404"
          title="文档不存在"
          subTitle="抱歉，您访问的文档无效或已被删除。"
          extra={<Button type="primary" onClick={() => navigate('/')}>返回首页</Button>}
        />
      </div>
    );
  }

  const getStatusTag = (status?: string) => {
    // 放弃 AntD 写死的颜色，改用可完美适配日夜间的自定义 CSS 样式
    switch (status) {
      case 'pending': 
        return <div className="custom-status-tag border-blue"><LoadingOutlined /> 生成中</div>;
      case 'generated': 
        return <div className="custom-status-tag border-green"><CheckCircleOutlined /> 生成完成</div>;
      case 'exported': 
        return <div className="custom-status-tag border-gray">已导出</div>;
      case 'failed': 
        return <div className="custom-status-tag border-red"><CloseCircleOutlined /> 生成失败</div>;
      default: 
        return <div className="custom-status-tag border-gray">状态未知</div>;
    }
  };

  const formatSize = (bytes?: number) => {
    if (!bytes) return '未知';
    if (bytes < 1024) return bytes + ' B';
    return (bytes / 1024).toFixed(2) + ' KB';
  };

  return (
    <div className="result-page">
      <div className="result-container glass-card noise-texture">
        {loading ? (
          <div className="result-loading">
            <Spin size="large" tip="加载文档信息中..." />
          </div>
        ) : doc ? (
          <>
            <div className="result-header">
              <Button type="text" icon={<LeftOutlined />} onClick={() => navigate(`/chat/${doc.session_id}`)} className="result-back-btn">
                返回聊天
              </Button>
              <div className="result-header-content">
                <div className="result-doc-icon">
                  <FileWordOutlined />
                </div>
                <div className="result-doc-info">
                  <h2 className="result-title">{doc.title || '未命名文档'}</h2>
                  <div className="result-meta-tags">
                    {getStatusTag(doc.status)}
                    {doc.file_size && doc.file_size > 0 ? (
                       <div className="custom-status-tag border-gray">{formatSize(doc.file_size)}</div>
                    ) : null}
                  </div>
                </div>
              </div>
            </div>

            <div className="result-content-area">
              <div className="result-info-grid">
                <div className="info-item">
                  <div className="info-label">
                    <span className="dot"></span>
                    文档标识
                  </div>
                  <div className="info-value doc-id-font">#{doc.id.substring(0,8)}</div>
                </div>
                <div className="info-item">
                  <div className="info-label">
                    <span className="dot"></span>
                    创建时间
                  </div>
                  <div className="info-value">{formatBeijingDateTime(doc.created_at)}</div>
                </div>
                <div className="info-item">
                  <div className="info-label">
                    <span className="dot"></span>
                    更新时间
                  </div>
                  <div className="info-value">{formatBeijingDateTime(doc.updated_at)}</div>
                </div>
              </div>

              <div className="result-mock-box">
                {doc.content ? (
                  <div className="result-content">
                    <MarkdownRenderer 
                      content={doc.content}
                      className="document-content"
                    />
                  </div>
                ) : (
                  <>
                    <div className="mock-shimmer"></div>
                    <p className="mock-text">
                      {doc.status === 'pending' ? '文档生成中，请稍候...' : '文档内容为空或正在处理。'}
                      <br/>
                      您可点击下方按钮尝试获取本地完整文件。
                    </p>
                  </>
                )}
              </div>
            </div>

            <div className="result-footer">
               <Button 
                type="primary" 
                size="large" 
                icon={<DownloadOutlined />} 
                loading={exporting}
                onClick={handleExport}
                className="result-download-btn press-effect"
                disabled={doc.status === 'pending'}
               >
                 下载诉状 (Word)
               </Button>
            </div>
          </>
        ) : null}
      </div>
    </div>
  );
}

// frontend/src/pages/ResultPage.vue
<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { NButton, NDescriptions, NDescriptionsItem, NEmpty, NSpin, NTag, useMessage } from 'naive-ui'
import { exportDocument, getDocument } from '@/services/documentService'
import type { DocumentResponse } from '@/services/documentService'
import MarkdownRenderer from '@/components/MarkdownRenderer.vue'

const route = useRoute()
const router = useRouter()
const message = useMessage()

const doc = ref<DocumentResponse | null>(null)
const loading = ref(true)
const exporting = ref(false)
const notFound = ref(false)

const docId = String(route.params.docId)

const statusMap: Record<string, { label: string; type: 'info' | 'success' | 'error' | 'warning' | 'default' }> = {
  pending: { label: '生成中', type: 'warning' },
  generated: { label: '已生成', type: 'success' },
  exported: { label: '已导出', type: 'info' },
  failed: { label: '生成失败', type: 'error' },
}

onMounted(async () => {
  await loadDoc()
})

async function loadDoc() {
  loading.value = true
  try {
    doc.value = await getDocument(docId)
  } catch {
    notFound.value = true
  } finally {
    loading.value = false
  }
}

function formatSize(size?: number | null): string {
  if (!size) return '-'
  if (size < 1024) return `${size} B`
  return `${(size / 1024).toFixed(1)} KB`
}

function formatTime(value: string): string {
  const date = new Date(value)
  if (Number.isNaN(date.getTime())) return value
  const pad = (n: number) => String(n).padStart(2, '0')
  return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())} ${pad(date.getHours())}:${pad(date.getMinutes())}`
}

async function handleExport() {
  if (!doc.value) return
  exporting.value = true
  try {
    const data = await exportDocument(doc.value.id)
    const link = document.createElement('a')
    link.href = data.download_url
    link.download = data.filename
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    message.success('开始下载')
    await loadDoc()
  } catch (error) {
    message.error(error instanceof Error ? error.message : '导出失败')
  } finally {
    exporting.value = false
  }
}
</script>

<template>
  <div class="result-page page-container">
    <n-spin :show="loading">
      <n-empty v-if="notFound" description="文档不存在" style="margin-top: 100px">
        <template #extra>
          <n-button type="primary" @click="router.push('/')">返回首页</n-button>
        </template>
      </n-empty>

      <div v-else-if="doc" class="result-card glass-card fade-in">
        <header class="result-header">
          <div class="result-title">
            <span class="doc-icon">📄</span>
            <div>
              <h2>{{ doc.title || '法律文书' }}</h2>
              <n-tag :bordered="false" :type="(statusMap[doc.status]?.type as any) || 'default'" size="small">
                {{ statusMap[doc.status]?.label || doc.status }}
              </n-tag>
            </div>
          </div>
          <n-button size="small" quaternary @click="router.push(`/chat/${doc.session_id}`)">
            ← 返回聊天
          </n-button>
        </header>

        <n-descriptions bordered size="small" :column="2" class="doc-meta">
          <n-descriptions-item label="文档 ID">{{ doc.id.slice(0, 8) }}…</n-descriptions-item>
          <n-descriptions-item label="模板">
            {{ doc.template_id }}
          </n-descriptions-item>
          <n-descriptions-item label="创建时间">{{ formatTime(doc.created_at) }}</n-descriptions-item>
          <n-descriptions-item label="文件大小">{{ formatSize(doc.file_size) }}</n-descriptions-item>
        </n-descriptions>

        <div class="doc-content">
          <div v-if="doc.status === 'pending'" class="doc-loading">
            <div class="mock-shimmer"></div>
            <div class="mock-shimmer short"></div>
            <div class="mock-shimmer"></div>
            <div class="mock-shimmer medium"></div>
          </div>
          <template v-else-if="doc.content">
            <MarkdownRenderer :content="doc.content" />
          </template>
          <n-empty v-else size="small" description="文档内容暂不可预览" />
        </div>

        <footer class="result-footer">
          <n-button
            type="primary"
            size="large"
            :loading="exporting"
            :disabled="doc.status === 'pending' || doc.status === 'failed'"
            @click="handleExport"
          >
            ⬇️ 下载诉状（Word）
          </n-button>
        </footer>
      </div>
    </n-spin>
  </div>
</template>

<style scoped>
.result-page {
  max-width: 860px;
}
.result-card {
  padding: 28px;
}
.result-header {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  margin-bottom: 20px;
}
.result-title {
  display: flex;
  align-items: center;
  gap: 14px;
}
.doc-icon {
  font-size: 36px;
}
.result-title h2 {
  margin: 0 0 4px;
  font-size: 20px;
}
.doc-meta {
  margin-bottom: 20px;
}
.doc-content {
  min-height: 200px;
  padding: 20px;
  border-radius: var(--radius-md);
  background: var(--bg-elevated);
  border: 1px solid var(--border-color);
}
.doc-loading {
  display: flex;
  flex-direction: column;
  gap: 12px;
}
.mock-shimmer {
  height: 16px;
  border-radius: 6px;
  background: linear-gradient(90deg, rgba(128, 128, 128, 0.1) 25%, rgba(128, 128, 128, 0.22) 50%, rgba(128, 128, 128, 0.1) 75%);
  background-size: 400% 100%;
  animation: shimmer 1.4s ease infinite;
}
.mock-shimmer.short {
  width: 60%;
}
.mock-shimmer.medium {
  width: 80%;
}
@keyframes shimmer {
  0% {
    background-position: 100% 0;
  }
  100% {
    background-position: -100% 0;
  }
}
.result-footer {
  margin-top: 24px;
  display: flex;
  justify-content: center;
}
@media print {
  .result-card {
    box-shadow: none;
    border: none;
  }
  .result-header,
  .result-footer,
  .doc-meta {
    display: none;
  }
}
</style>
